FROM php:8.2-apache
# Mise à jour du système d'exploitation et installation des dépendances
RUN apt-get update && apt-get upgrade -y && apt-get install -y \
    libzip-dev \
    zip \
    unzip
# Installation des extensions PHP nécessaires
RUN docker-php-ext-install pdo_mysql mysqli

# Activation des extensions PHP
RUN docker-php-ext-enable pdo_mysql mysqli

# Exposer le port 80
EXPOSE 80